extends Sprite

var pressed = false

func _ready():
	pass

func placeTrap(trap):
	add_child(trap)

func placeWall(pos):
	var map = get_node("autogeneratedTileMap")
	pos.x = pos.x / 32
	pos.y = pos.y / 32
	return map.placeWall(pos)

func set_start():
	var hero = get_node("hero")
	var map = get_node("autogeneratedTileMap")
	hero.set_map(map)
	hero.set_pos(map.get_start())

func remove_obstacles():
	var children = get_children()
	for child in children:
		if(child.is_in_group("obstacle")):
			child.queue_free()

func resetmap():
	get_node("autogeneratedTileMap").generateMap()
	remove_obstacles()
	set_start()
	var hero = get_node("hero")
	hero.respawn()
